workflows:
  android_apk:
    name: Android APK (Debug)
    max_build_duration: 60
    instance_type: linux
    environment:
      java: 17
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
        - $HOME/.android/build-cache
    scripts:
      - name: Make Gradle wrapper executable
        script: |
          chmod +x ./gradlew
      - name: Print tool versions
        script: |
          java -version || true
          ./gradlew --version || true
      - name: Build debug APK
        script: |
          ./gradlew --no-daemon clean assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
      - app/build/outputs/apk/debug/output-metadata.json

