workflows:
  android_debug:
    name: Android Debug
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      java: 17
      vars:
        JAVA_VERSION: 17
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
        - $HOME/.android/build-cache
    scripts:
      - name: Make Gradle wrapper executable
        script: |
          chmod +x ./gradlew
      - name: Print tool versions
        script: |
          java -version || true
          ./gradlew --version || true
      - name: Build debug APK
        script: |
          ./gradlew --no-daemon clean assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
      - app/build/outputs/apk/debug/output-metadata.json

  # Optional release workflow (requires setting signing variables in Codemagic UI)
  android_release:
    name: Android Release (Signed)
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      java: 17
      vars:
        JAVA_VERSION: 17
        # Provide these in Codemagic UI as secure environment variables:
        # CM_KEYSTORE: base64-encoded keystore file
        # CM_KEYSTORE_PASSWORD: keystore password
        # CM_KEY_ALIAS: key alias
        # CM_KEY_PASSWORD: key password
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
        - $HOME/.android/build-cache
    scripts:
      - name: Prepare signing files
        script: |
          if [ -n "$CM_KEYSTORE" ]; then
            echo "$CM_KEYSTORE" | base64 -d > $CM_BUILD_DIR/keystore.jks
          fi
      - name: Make Gradle wrapper executable
        script: |
          chmod +x ./gradlew
      - name: Build release APK
        script: |
          ./gradlew --no-daemon clean assembleRelease \
            -Pandroid.injected.signing.store.file=$CM_BUILD_DIR/keystore.jks \
            -Pandroid.injected.signing.store.password=$CM_KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$CM_KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$CM_KEY_PASSWORD
    artifacts:
      - app/build/outputs/apk/release/*.apk
      - app/build/outputs/mapping/release/mapping.txt

